# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MinderApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MinderApp
  pod 'Firebase/Core'

  target 'MinderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MinderApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MinderApp-tvOS

  target 'MinderApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
